# Generated by Django 3.2.3 on 2021-06-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_cart', models.BooleanField(default=False)),
                ('tags', models.TextField()),
                ('description', models.JSONField(default=None)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
            ],
        ),
    ]
