"""
    NOTE
    File is auto generated by Django Framework.
    I did not edit this file
"""

from django.apps import AppConfig


class StoreConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'Store'
