"""
    NOTE
    File is auto generated by Django Framework.
    I did not edit this file
"""

"""
ASGI config for ArtSite project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ArtSite.settings')

application = get_asgi_application()
